server:
  port: 8782
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign-client:
  ribbon:
    #负载均衡策略， RandomRule:随机,RoundRobinRule:轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
feign:
  hystrix:
    enabled: true