server:
  port: 8761
eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
  instance:
    hostname: 192.168.31.236
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    perferIpAddress: true
  security:
    basic:
      enabled: false
    user:
      name: admin
      password: admin
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.security.user.name}:${eureka.security.user.password}${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
