server:
  port: 8801
zuul:
  routes:
    api-1:
      path: /api-client1/**
      serviceId: feign-Server
    api-2:
      path: /api-client2/**
      serviceId: feign-Server
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

      